apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipemaker-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: recipemaker-app
  template:
    metadata:
      labels:
        app: recipemaker-app
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP