apiVersion: v1
kind: Service
metadata:
  name: recipemaker-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: recipemaker-app